[build]
  command = "npm run build"
  publish = "public"
  ignore = "bash netlify-ignore.sh"

[build.environment]
  HUGO_VERSION = "0.152.2"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "20"

# Redirects (optional)
# [[redirects]]
#   from = "/"
#   to = "/index.html"
#   status = 200
#   force = true
